### ISSUE TITLE
Preprocessor directives?

### ISSUE THREAD

**Issue by e3b0c442** [leighmcculloch/keywords#8]
Hi there.

I like that this data set is being compiled.

One thing I noticed though -- C++ includes the preprocessor directives in its list of reserved keywords, while C does not include these. Given that these words are reserved by the preprocessor and not the language itself, I feel that their inclusion is not entirely appropriate. That said, either way the inclusion of the preprocessor directives in one but not the other seems inappropriate.

Happy to open a PR to correct this, but I thought it might be good to discuss first.

**Comment by leighmcculloch** [comment]
Hey @e3b0c442! If you'd like to open to a PR with the correction that'd be most welcome! I don't think the preprocessors are the same for both C and C++, could you include some references in the PR as well? Thanks!

**Comment by e3b0c442** [comment]
So... I may have gotten carried away. 🤣

I got a wee bit frustrated trying to fix and format the list and moved the raw data into a YAML file, and created a Go template based on your README.txt to create a README.md from the YAML data. In the process of trying to get a full build without interaction I switched to a graphical bar chart as well. Finally, I dug up sources for each of the languages and added those for each language (as well as adding a couple of languages).

The end result is... a pretty complete overhaul of what you had originally put together. I can open a PR if you would like to adopt the changes, or just keep it for myself if you don't. Completely up to you.

https://github.com/e3b0c442/keywords/tree/template

**Comment by leighmcculloch** [comment]
![](https://i.jif.wtf/10.4fe01cc7ca603ad149f209b386d35efb.gif)

Wow! That is amazing. That's such a work of art. I think you've done such a mammoth job you should merge it to your master and I'll add a link in my README to your fork.

**Comment by e3b0c442** [comment]
It's done. Thanks for the inspiration.

**Comment by leighmcculloch** [comment]
👏 No worries. I added a link to your repository on mine. 817085b0222ac8656a617e4b457338a394707af0
